application: whosup
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- deferred: on
- remote_api: on

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: endpoints.APPLICATION

libraries:
- name: pycrypto
  version: "2.6"
- name: django
  version: "1.4"
