application: whosup
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: endpoints.APPLICATION

libraries:
- name: pycrypto
  version: "2.6"
