application: balancebot-eu
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: webob
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest

includes:
- mysql_settings.yaml

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: endpoints.API

- url: /static
  static_dir: static
  expiration: "7d"

- url: /admin/.*
  script: main.ADMIN_APPLICATION
  login: admin

- url: /.*
  script: main.APPLICATION



